# This is a basic workflow to help you get started with Actions

name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sphinx_version: ["", "~=3.0.0", "~=2.4.0", "~=2.1.0"]
        python_version: ["3.6", "3.8"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx${{matrix.sphinx_version}}
          pip install .
      - name: List dependency versions
        run: |
          python -V
          pip list
      # Runs a set of commands using the runners shell
      - name: Build and fail on errors
        run: |
          make html SPHINXOPTS="-W --keep-going -T -v"